// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCv93-laqSW3EGU2-dh5evo2Bm1CWxBulU',
    appId: '1:77851175495:web:fc370d3c69023a2f1b9f62',
    messagingSenderId: '77851175495',
    projectId: 'masr-a7la-2023',
    authDomain: 'masr-a7la-2023.firebaseapp.com',
    storageBucket: 'masr-a7la-2023.appspot.com',
    measurementId: 'G-KW8W5TJPD8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB6oAX0OHX-7XJVEyyLoBvA5UFqro-XrwQ',
    appId: '1:77851175495:android:fbbf9719966e3bcc1b9f62',
    messagingSenderId: '77851175495',
    projectId: 'masr-a7la-2023',
    storageBucket: 'masr-a7la-2023.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBAvbDoA8cZkhB9G1n11hoXskTDidI4XZI',
    appId: '1:77851175495:ios:5d0b7d897a0319bb1b9f62',
    messagingSenderId: '77851175495',
    projectId: 'masr-a7la-2023',
    storageBucket: 'masr-a7la-2023.appspot.com',
    iosClientId: '77851175495-mcoc5hianloo15ih0gu96mo6bb40koh0.apps.googleusercontent.com',
    iosBundleId: 'com.example.masrA7la',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBAvbDoA8cZkhB9G1n11hoXskTDidI4XZI',
    appId: '1:77851175495:ios:5d0b7d897a0319bb1b9f62',
    messagingSenderId: '77851175495',
    projectId: 'masr-a7la-2023',
    storageBucket: 'masr-a7la-2023.appspot.com',
    iosClientId: '77851175495-mcoc5hianloo15ih0gu96mo6bb40koh0.apps.googleusercontent.com',
    iosBundleId: 'com.example.masrA7la',
  );
}
